// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { CropDTO } from '@app/model/bw/co/sigmaproduce/crop/crop-dto';
import { CropListDTO } from '@app/model/bw/co/sigmaproduce/crop/crop-list-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class CropApi {
    
    protected path = '/crop';

    private http = inject(HttpClient);

    public findByCropTypes(cropTypeIds: Set<string> | any ): Observable<CropListDTO[] | any[]> {

        return this.http.get<CropListDTO[] | any[]>(`${this.path}/types?cropTypeIds=${cropTypeIds}`);
    }

    public findById(id: string | any ): Observable<CropDTO | any> {

        return this.http.get<CropDTO | any>(`${this.path}/${id}`);
    }

    public findByIssueType(issueType: CropIssueType | any ): Observable<CropListDTO[] | any[]> {

        return this.http.get<CropListDTO[] | any[]>(`${this.path}/issue/type?issueType=${issueType}`);
    }

    public getAll(): Observable<CropListDTO[] | any[]> {

        return this.http.get<CropListDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<CropListDTO> | any> {

        return this.http.get<Page<CropListDTO> | any>(`${this.path}/page/${pageNumber}/size/${pageSize}`);
    }

    public pagedSearch(pageNumber: number | any , pageSize: number | any , criteria: string | any ): Observable<Page<CropListDTO> | any> {

        return this.http.get<Page<CropListDTO> | any>(`${this.path}/search/page/${pageNumber}/size/${pageSize}?criteria=${criteria}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(crop: CropDTO | any ): Observable<CropDTO | any> {

        return this.http.post<CropDTO | any>(`${this.path}`, crop);
    }

    public search(criteria: string | any ): Observable<CropListDTO[] | any[]> {

        return this.http.post<CropListDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`, criteria);
    }

}
