// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand! hibernate4or5=true hibernateVersion=6.1.6.Final
// Generated by hibernate/SpringHibernateDaoBase.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.crop.type;

/**
 * <p>
 * Base Spring DAO Class: is able to create, update, remove, load, and find
 * objects of type <code>bw.co.sigmaproduce.crop.type.CropType</code>.
 * </p>
 *
 * @see bw.co.sigmaproduce.crop.type.CropType
 */
public abstract class CropTypeDaoBase
    implements bw.co.sigmaproduce.crop.type.CropTypeDao
{

    protected final org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(CropTypeDaoBase.class);

    protected final bw.co.sigmaproduce.crop.type.CropTypeRepository cropTypeRepository;

    protected bw.co.sigmaproduce.crop.CropDao cropDao;
    protected final bw.co.sigmaproduce.crop.CropRepository cropRepository;

    protected bw.co.sigmaproduce.crop.issue.CropIssueDao cropIssueDao;
    protected final bw.co.sigmaproduce.crop.issue.CropIssueRepository cropIssueRepository;

    public CropTypeDaoBase(
        bw.co.sigmaproduce.crop.CropRepository cropRepository,
        bw.co.sigmaproduce.crop.issue.CropIssueRepository cropIssueRepository,
        bw.co.sigmaproduce.crop.type.CropTypeRepository cropTypeRepository
    ) {
        this.cropTypeRepository = cropTypeRepository;
        this.cropRepository = cropRepository;
        this.cropIssueRepository = cropIssueRepository;
    }

    /**
     * Sets the reference to <code>cropDao</code>.
     * @param cropDaoIn
     */
    @org.springframework.beans.factory.annotation.Autowired
    public void setCropDao(@org.springframework.context.annotation.Lazy bw.co.sigmaproduce.crop.CropDao cropDaoIn)
    {
        this.cropDao = cropDaoIn;
    }
    
    /**
     * Gets the reference to <code>cropDao</code>.
     * @return cropDao
     */
    protected bw.co.sigmaproduce.crop.CropDao getCropDao()
    {
        return this.cropDao;
    }

    /**
     * Gets the reference to <code>cropRepository</code>.
     * @return cropRepository
     */
    protected bw.co.sigmaproduce.crop.CropRepository getCropRepository()
    {
        return this.cropRepository;
    }

    /**
     * Sets the reference to <code>cropIssueDao</code>.
     * @param cropIssueDaoIn
     */
    @org.springframework.beans.factory.annotation.Autowired
    public void setCropIssueDao(@org.springframework.context.annotation.Lazy bw.co.sigmaproduce.crop.issue.CropIssueDao cropIssueDaoIn)
    {
        this.cropIssueDao = cropIssueDaoIn;
    }
    
    /**
     * Gets the reference to <code>cropIssueDao</code>.
     * @return cropIssueDao
     */
    protected bw.co.sigmaproduce.crop.issue.CropIssueDao getCropIssueDao()
    {
        return this.cropIssueDao;
    }

    /**
     * Gets the reference to <code>cropIssueRepository</code>.
     * @return cropIssueRepository
     */
    protected bw.co.sigmaproduce.crop.issue.CropIssueRepository getCropIssueRepository()
    {
        return this.cropIssueRepository;
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Object get(final int transform, final java.lang.String id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "CropType.get - 'id' can not be null");
        }
        java.util.Optional<bw.co.sigmaproduce.crop.type.CropType> entity = cropTypeRepository.findById(id);
        return transformEntity(transform, entity.get());
    }
    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType get(java.lang.String id)
    {
        return (bw.co.sigmaproduce.crop.type.CropType)this.get(TRANSFORM_NONE, id);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object load(final int transform, final java.lang.String id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "CropType.load - 'id' can not be null");
        }
        java.util.Optional<bw.co.sigmaproduce.crop.type.CropType> entity = cropTypeRepository.findById(id);
        return transformEntity(transform, entity.get());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType load(java.lang.String id)
    {
        return (bw.co.sigmaproduce.crop.type.CropType)this.load(TRANSFORM_NONE, id);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> loadAll()
    {
        return (java.util.Collection<bw.co.sigmaproduce.crop.type.CropType>) this.loadAll(bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.Collection<?> loadAll(final int transform)
    {
        return this.loadAll(transform, -1, -1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.Collection<?> loadAll(final int pageNumber, final int pageSize)
    {
        return this.loadAll(bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE, pageNumber, pageSize);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.Collection<?> loadAll(final int transform, final int pageNumber, final int pageSize)
    {
		
        final java.util.Collection<?> results = cropTypeRepository.findAll();
        this.transformEntities(transform, results);
        return results;
    }

    /**
     * firstResult = (pageNumber - 1) * pageSize
     * @param pageNumber
     * @param pageSize
     * @return firstResult
     */
    protected int calculateFirstResult(int pageNumber, int pageSize)
    {
        int firstResult = 0;
        if (pageNumber > 0)
        {
            firstResult = (pageNumber - 1) * pageSize;
        }
        return firstResult;
    }

    /**
     * prePersist event - This method is called before creating the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _prePersist(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * postPersist event - This method is called after creating the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _postPersist(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * preUpdate event - This method is called before updating the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _preUpdate(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * postUpdate event - This method is called after updating the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _postUpdate(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * preRemove event - This method is called before deleting the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _preRemove(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * postRemove event - This method is called after deleting the entity
     * @param cropType bw.co.sigmaproduce.crop.type.CropType
     */
    protected void _postRemove(final bw.co.sigmaproduce.crop.type.CropType cropType)
    {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType create(bw.co.sigmaproduce.crop.type.CropType cropType)
    {
        return (bw.co.sigmaproduce.crop.type.CropType)this.create(bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE, cropType);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object create(final int transform, bw.co.sigmaproduce.crop.type.CropType cropType)
    {
        if (cropType == null)
        {
            throw new IllegalArgumentException(
                "CropType.create - 'cropType' can not be null");
        }

        //prePersist event
        _prePersist(cropType);

        cropType = this.cropTypeRepository.save(cropType);

        //postPersist event
        _postPersist(cropType);

        return this.transformEntity(transform, cropType);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> create(final java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        return (java.util.Collection<bw.co.sigmaproduce.crop.type.CropType>) create(bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE, entities);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.Collection<?> create(final int transform, final java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "CropType.create - 'entities' can not be null");
        }
        java.util.Collection<Object> transformed = new java.util.ArrayList<Object>();
        for (bw.co.sigmaproduce.crop.type.CropType entity : entities)
        {
            transformed.add(create(transform, entity));
        }
        return transformed;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType create(
        java.lang.String createdBy,
        java.lang.String updatedBy,
        java.time.LocalDateTime updatedDate,
        java.time.LocalDateTime createdDate,
        java.lang.String code,
        java.util.Collection<java.io.File> images,
        java.lang.String description,
        java.lang.String name)
    {
        return (bw.co.sigmaproduce.crop.type.CropType)this.create(bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE, createdBy, updatedBy, updatedDate, createdDate, code, images, description, name);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object create(
        final int transform,
        java.lang.String createdBy,
        java.lang.String updatedBy,
        java.time.LocalDateTime updatedDate,
        java.time.LocalDateTime createdDate,
        java.lang.String code,
        java.util.Collection<java.io.File> images,
        java.lang.String description,
        java.lang.String name)
    {
        bw.co.sigmaproduce.crop.type.CropType entity = new bw.co.sigmaproduce.crop.type.CropType();
        entity.setCreatedBy(createdBy);
        entity.setUpdatedBy(updatedBy);
        entity.setUpdatedDate(updatedDate);
        entity.setCreatedDate(createdDate);
        entity.setCode(code);
        entity.setImages(images);
        entity.setDescription(description);
        entity.setName(name);
        return this.create(transform, entity);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void update(bw.co.sigmaproduce.crop.type.CropType cropType)
    {
        if (cropType == null)
        {
            throw new IllegalArgumentException(
                "CropType.update - 'cropType' can not be null");
        }

        //preUpdate event
        _preUpdate(cropType);

        cropType = this.cropTypeRepository.save(cropType);

        //postUpdate event
        _postUpdate(cropType);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void update(final java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "CropType.update - 'entities' can not be null");
        }
        for (bw.co.sigmaproduce.crop.type.CropType entity : entities)
        {
            update(entity);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void remove(bw.co.sigmaproduce.crop.type.CropType cropType)
    {
        if (cropType == null)
        {
            throw new IllegalArgumentException(
                "CropType.remove - 'cropType' can not be null");
        }
        //preRemove event
        _preRemove(cropType);

        this.cropTypeRepository.delete(cropType);

        //postRemove event
        _postRemove(cropType);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void remove(java.lang.String id)
    {
        if (id == null)
        {
            throw new IllegalArgumentException(
                "CropType.remove - 'id' can not be null");
        }
        bw.co.sigmaproduce.crop.type.CropType entity = this.get(id);
        if (entity != null)
        {
            this.remove(entity);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void remove(java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        if (entities == null)
        {
            throw new IllegalArgumentException(
                "CropType.remove - 'entities' can not be null");
        }
        for (bw.co.sigmaproduce.crop.type.CropType entity : entities)
        {
            //preRemove event
            _preRemove(entity);

            this.cropTypeRepository.delete(entity);

            //postRemove event
            _postRemove(entity);
        }
    }
    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> findByCriteria(final java.lang.String criteria)
    {
        try
        {
            return this.handleFindByCriteria(criteria);
        }
        catch (Throwable th)
        {
            throw new RuntimeException(
            "Error performing 'bw.co.sigmaproduce.crop.type.CropTypeDao.findByCriteria(java.lang.String criteria)' --> " + th,
            th);
        }
    }

    /**
     * Performs the core logic for {@link #findByCriteria(java.lang.String)}
     * @param criteria
     * @return java.util.Collection<bw.co.sigmaproduce.crop.type.CropType>
     * @throws Exception
     */
    protected abstract java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> handleFindByCriteria(java.lang.String criteria)
        throws Exception;

    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>bw.co.sigmaproduce.crop.type.CropTypeDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     * <p>
     * This method will return instances of these types:
     * <ul>
     *   <li>{@link bw.co.sigmaproduce.crop.type.CropType} - {@link #TRANSFORM_NONE}</li>
     *   <li>{@link bw.co.sigmaproduce.crop.type.CropTypeVO} - {@link #TRANSFORM_CROPTYPEVO}</li>
     *   <li>{@link bw.co.sigmaproduce.crop.type.CropTypeListVO} - {@link #TRANSFORM_CROPTYPELISTVO}</li>
     * </ul>
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link bw.co.sigmaproduce.crop.type.CropTypeDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see bw.co.sigmaproduce.crop.type.CropTypeDao#transformEntity(int, bw.co.sigmaproduce.crop.type.CropType)
     */
    @Override
    public Object transformEntity(final int transform, final bw.co.sigmaproduce.crop.type.CropType entity)
    {
        Object target = null;
        if (entity != null)
        {
            switch (transform)
            {
                case TRANSFORM_CROPTYPEVO :
                    target = toCropTypeVO(entity);
                    break;
                case TRANSFORM_CROPTYPELISTVO :
                    target = toCropTypeListVO(entity);
                    break;
                case bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE : // fall-through
                default:
                    target = entity;
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void transformEntities(final int transform, final java.util.Collection<?> entities)
    {
        switch (transform)
        {
            case TRANSFORM_CROPTYPEVO :
                org.apache.commons.collections4.CollectionUtils.transform(entities, this.CROPTYPEVO_TRANSFORMER);
                break;
            case TRANSFORM_CROPTYPELISTVO :
                org.apache.commons.collections4.CollectionUtils.transform(entities, this.CROPTYPELISTVO_TRANSFORMER);
                break;
            case bw.co.sigmaproduce.crop.type.CropTypeDao.TRANSFORM_NONE : // fall-through
                default:
                // do nothing;
        }
    }

    /**
     * @see bw.co.sigmaproduce.crop.type.CropTypeDao#toEntities(java.util.Collection)
     */
    @Override
    public void toEntities(final java.util.Collection<?> results)
    {
        if (results != null)
        {
            org.apache.commons.collections4.CollectionUtils.transform(results, this.ENTITYTRANSFORMER);
        }
    }

    /**
     * This anonymous transformer is designed to transform report query results
     * (which result in an array of entities) to {@link bw.co.sigmaproduce.crop.type.CropType}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private org.apache.commons.collections4.Transformer ENTITYTRANSFORMER =
        new org.apache.commons.collections4.Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toEntity(rows);
                }
                else if (input instanceof bw.co.sigmaproduce.crop.type.CropType)
                {
                    result = input;
                }
                return result;
            }
        };

    /**
     * @param row
     * @return bw.co.sigmaproduce.crop.type.CropType
     */
    protected bw.co.sigmaproduce.crop.type.CropType toEntity(Object[] row)
    {
        bw.co.sigmaproduce.crop.type.CropType target = null;
        if (row != null)
        {
            final int numberOfObjects = row.length;
            for (int ctr = 0; ctr < numberOfObjects; ctr++)
            {
                final Object object = row[ctr];
                if (object instanceof bw.co.sigmaproduce.crop.type.CropType)
                {
                    target = (bw.co.sigmaproduce.crop.type.CropType)object;
                    break;
                }
            }
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<bw.co.sigmaproduce.crop.type.CropTypeVO> toCropTypeVOCollection(java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        if (entities == null)
        {
            return null;
        }
        @SuppressWarnings("rawtypes")
        java.util.Collection result = new java.util.ArrayList(entities);
        org.apache.commons.collections4.CollectionUtils.transform(result, this.CROPTYPEVO_TRANSFORMER);
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({ "unchecked" })
    public bw.co.sigmaproduce.crop.type.CropTypeVO[] toCropTypeVOArray(java.util.Collection<?> entities)
    {
        bw.co.sigmaproduce.crop.type.CropTypeVO[] result = null;
        if (entities != null)
        {
        @SuppressWarnings("rawtypes")
            final java.util.Collection collection = new java.util.ArrayList(entities);
            this.toCropTypeVOCollection(collection);
            result = (bw.co.sigmaproduce.crop.type.CropTypeVO[]) collection.toArray(new bw.co.sigmaproduce.crop.type.CropTypeVO[collection.size()]);
        }
        return result;
    }

    /**
     * Default implementation for transforming the results of a report query into a value object. This
     * implementation exists for convenience reasons only. It needs only be overridden in the
     * {@link CropTypeDaoImpl} class if you intend to use reporting queries.
     * @param row
     * @return toCropTypeVO(this.toEntity(row))
     * @see bw.co.sigmaproduce.crop.type.CropTypeDao#toCropTypeVO(bw.co.sigmaproduce.crop.type.CropType)
     */
    protected bw.co.sigmaproduce.crop.type.CropTypeVO toCropTypeVO(Object[] row)
    {
        return this.toCropTypeVO(this.toEntity(row));
    }

    /**
     * This anonymous transformer is designed to transform entities or report query results
     * (which result in an array of objects) to {@link bw.co.sigmaproduce.crop.type.CropTypeVO}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private org.apache.commons.collections4.Transformer CROPTYPEVO_TRANSFORMER =
        new org.apache.commons.collections4.Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof bw.co.sigmaproduce.crop.type.CropType)
                {
                    final bw.co.sigmaproduce.crop.type.CropType entity = (bw.co.sigmaproduce.crop.type.CropType)input;
                    result = toCropTypeVO(entity);
                }
                else if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toCropTypeVO(rows);
                }
                return result;
            }
        };

    /**
     * {@inheritDoc}
     */
    @Override
    public void cropTypeVOToEntityCollection(java.util.Collection<?> instances)
    {
        if (instances != null)
        {
            for (final java.util.Iterator<?> iterator = instances.iterator(); iterator.hasNext();)
            {
                // - remove an objects that are null or not of the correct instance
                if (!(iterator.next() instanceof bw.co.sigmaproduce.crop.type.CropTypeVO))
                {
                    iterator.remove();
                }
            }
            org.apache.commons.collections4.CollectionUtils.transform(instances, this.CropTypeVOToEntityTransformer);
        }
    }

    private final org.apache.commons.collections4.Transformer CropTypeVOToEntityTransformer =
        new org.apache.commons.collections4.Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                return cropTypeVOToEntity((bw.co.sigmaproduce.crop.type.CropTypeVO)input);
            }
        };


    /**
     * {@inheritDoc}
     */
    @Override
    public void toCropTypeVO(
        bw.co.sigmaproduce.crop.type.CropType source,
        bw.co.sigmaproduce.crop.type.CropTypeVO target)
    {
        target.setCode(source.getCode());
        target.setId(source.getId());
        target.setName(source.getName());
        target.setCreatedBy(source.getCreatedBy());
        target.setUpdatedBy(source.getUpdatedBy());
        target.setCreatedDate(source.getCreatedDate());
        target.setUpdatedDate(source.getUpdatedDate());
        if(org.apache.commons.collections4.CollectionUtils.isNotEmpty(target.getImages())){
            target.getImages().clear();
        } else {
            target.setImages(new java.util.ArrayList<>());
        }
        
        if(null!=source.getImages()) {
            target.getImages().addAll(source.getImages());
        }
        target.setDescription(source.getDescription());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropTypeVO toCropTypeVO(final bw.co.sigmaproduce.crop.type.CropType entity)
    {
        bw.co.sigmaproduce.crop.type.CropTypeVO target = null;
        if (entity != null)
        {
            target =  new bw.co.sigmaproduce.crop.type.CropTypeVO();
            this.toCropTypeVO(entity, target);
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void cropTypeVOToEntity(
        bw.co.sigmaproduce.crop.type.CropTypeVO source,
        bw.co.sigmaproduce.crop.type.CropType target,
        boolean copyIfNull)
    {
        if (copyIfNull || source.getCreatedBy() != null)
        {
            target.setCreatedBy(source.getCreatedBy());
        }
        if (copyIfNull || source.getUpdatedBy() != null)
        {
            target.setUpdatedBy(source.getUpdatedBy());
        }
        if (copyIfNull || source.getUpdatedDate() != null)
        {
            target.setUpdatedDate(source.getUpdatedDate());
        }
        if (copyIfNull || source.getCreatedDate() != null)
        {
            target.setCreatedDate(source.getCreatedDate());
        }
        if (copyIfNull || source.getCode() != null)
        {
            target.setCode(source.getCode());
        }
        if (copyIfNull || source.getImages() != null)
        {
            if(org.apache.commons.collections4.CollectionUtils.isNotEmpty(target.getImages())){
                target.getImages().clear();
            } else {
                target.setImages(new java.util.ArrayList<>());
            }
            if(null != source.getImages()) {
                target.getImages().addAll(source.getImages());
            }
        }
        if (copyIfNull || source.getDescription() != null)
        {
            target.setDescription(source.getDescription());
        }
        if (copyIfNull || source.getName() != null)
        {
            target.setName(source.getName());
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({"unchecked"})
    public java.util.Collection<bw.co.sigmaproduce.crop.type.CropTypeListVO> toCropTypeListVOCollection(java.util.Collection<bw.co.sigmaproduce.crop.type.CropType> entities)
    {
        if (entities == null)
        {
            return null;
        }
        @SuppressWarnings("rawtypes")
        java.util.Collection result = new java.util.ArrayList(entities);
        org.apache.commons.collections4.CollectionUtils.transform(result, this.CROPTYPELISTVO_TRANSFORMER);
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    @SuppressWarnings({ "unchecked" })
    public bw.co.sigmaproduce.crop.type.CropTypeListVO[] toCropTypeListVOArray(java.util.Collection<?> entities)
    {
        bw.co.sigmaproduce.crop.type.CropTypeListVO[] result = null;
        if (entities != null)
        {
        @SuppressWarnings("rawtypes")
            final java.util.Collection collection = new java.util.ArrayList(entities);
            this.toCropTypeListVOCollection(collection);
            result = (bw.co.sigmaproduce.crop.type.CropTypeListVO[]) collection.toArray(new bw.co.sigmaproduce.crop.type.CropTypeListVO[collection.size()]);
        }
        return result;
    }

    /**
     * Default implementation for transforming the results of a report query into a value object. This
     * implementation exists for convenience reasons only. It needs only be overridden in the
     * {@link CropTypeDaoImpl} class if you intend to use reporting queries.
     * @param row
     * @return toCropTypeListVO(this.toEntity(row))
     * @see bw.co.sigmaproduce.crop.type.CropTypeDao#toCropTypeListVO(bw.co.sigmaproduce.crop.type.CropType)
     */
    protected bw.co.sigmaproduce.crop.type.CropTypeListVO toCropTypeListVO(Object[] row)
    {
        return this.toCropTypeListVO(this.toEntity(row));
    }

    /**
     * This anonymous transformer is designed to transform entities or report query results
     * (which result in an array of objects) to {@link bw.co.sigmaproduce.crop.type.CropTypeListVO}
     * using the Jakarta Commons-Collections Transformation API.
     */
    private org.apache.commons.collections4.Transformer CROPTYPELISTVO_TRANSFORMER =
        new org.apache.commons.collections4.Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                Object result = null;
                if (input instanceof bw.co.sigmaproduce.crop.type.CropType)
                {
                    final bw.co.sigmaproduce.crop.type.CropType entity = (bw.co.sigmaproduce.crop.type.CropType)input;
                    result = toCropTypeListVO(entity);
                }
                else if (input instanceof Object[])
                {
                    final Object[] rows = (Object[])input;
                    result = toCropTypeListVO(rows);
                }
                return result;
            }
        };

    /**
     * {@inheritDoc}
     */
    @Override
    public void cropTypeListVOToEntityCollection(java.util.Collection<?> instances)
    {
        if (instances != null)
        {
            for (final java.util.Iterator<?> iterator = instances.iterator(); iterator.hasNext();)
            {
                // - remove an objects that are null or not of the correct instance
                if (!(iterator.next() instanceof bw.co.sigmaproduce.crop.type.CropTypeListVO))
                {
                    iterator.remove();
                }
            }
            org.apache.commons.collections4.CollectionUtils.transform(instances, this.CropTypeListVOToEntityTransformer);
        }
    }

    private final org.apache.commons.collections4.Transformer CropTypeListVOToEntityTransformer =
        new org.apache.commons.collections4.Transformer()
        {
            @Override
            public Object transform(Object input)
            {
                return cropTypeListVOToEntity((bw.co.sigmaproduce.crop.type.CropTypeListVO)input);
            }
        };


    /**
     * {@inheritDoc}
     */
    @Override
    public void toCropTypeListVO(
        bw.co.sigmaproduce.crop.type.CropType source,
        bw.co.sigmaproduce.crop.type.CropTypeListVO target)
    {
        target.setCode(source.getCode());
        target.setId(source.getId());
        target.setName(source.getName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropTypeListVO toCropTypeListVO(final bw.co.sigmaproduce.crop.type.CropType entity)
    {
        bw.co.sigmaproduce.crop.type.CropTypeListVO target = null;
        if (entity != null)
        {
            target =  new bw.co.sigmaproduce.crop.type.CropTypeListVO();
            this.toCropTypeListVO(entity, target);
        }
        return target;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void cropTypeListVOToEntity(
        bw.co.sigmaproduce.crop.type.CropTypeListVO source,
        bw.co.sigmaproduce.crop.type.CropType target,
        boolean copyIfNull)
    {
        if (copyIfNull || source.getCode() != null)
        {
            target.setCode(source.getCode());
        }
        if (copyIfNull || source.getName() != null)
        {
            target.setName(source.getName());
        }
    }

    /**
     * Gets the current <code>principal</code> if one has been set,
     * otherwise returns <code>null</code>.
     *
     * @return the current principal
     */
    protected java.security.Principal getPrincipal()
    {
        return bw.co.sigmaproduce.PrincipalStore.get();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType searchUniqueCode(final java.lang.String code)
    {

        org.springframework.data.jpa.domain.Specification<bw.co.sigmaproduce.crop.type.CropType> spec = bw.co.sigmaproduce.SigmaproduceSpecifications.<bw.co.sigmaproduce.crop.type.CropType, java.lang.String>findByAttribute(code, "code");
        java.util.List<bw.co.sigmaproduce.crop.type.CropType> entities = cropTypeRepository.findAll(spec, org.springframework.data.domain.Sort.by("code"));
        if(org.apache.commons.collections4.CollectionUtils.isEmpty(entities)) {
            return null;
        }

        return entities.get(0);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object searchUniqueCode(final int transform, final java.lang.String code)
    {
        final bw.co.sigmaproduce.crop.type.CropType entity=this.searchUniqueCode(code);
        if(entity == null)
        {
            return null;
        }
        return transformEntity(transform, entity);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType searchUniqueImages(final java.io.File images)
    {

        org.springframework.data.jpa.domain.Specification<bw.co.sigmaproduce.crop.type.CropType> spec = bw.co.sigmaproduce.SigmaproduceSpecifications.<bw.co.sigmaproduce.crop.type.CropType, java.io.File>findByAttribute(images, "images");
        java.util.List<bw.co.sigmaproduce.crop.type.CropType> entities = cropTypeRepository.findAll(spec, org.springframework.data.domain.Sort.by("images"));
        if(org.apache.commons.collections4.CollectionUtils.isEmpty(entities)) {
            return null;
        }

        return entities.get(0);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object searchUniqueImages(final int transform, final java.io.File images)
    {
        final bw.co.sigmaproduce.crop.type.CropType entity=this.searchUniqueImages(images);
        if(entity == null)
        {
            return null;
        }
        return transformEntity(transform, entity);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType searchUniqueName(final java.lang.String name)
    {

        org.springframework.data.jpa.domain.Specification<bw.co.sigmaproduce.crop.type.CropType> spec = bw.co.sigmaproduce.SigmaproduceSpecifications.<bw.co.sigmaproduce.crop.type.CropType, java.lang.String>findByAttribute(name, "name");
        java.util.List<bw.co.sigmaproduce.crop.type.CropType> entities = cropTypeRepository.findAll(spec, org.springframework.data.domain.Sort.by("name"));
        if(org.apache.commons.collections4.CollectionUtils.isEmpty(entities)) {
            return null;
        }

        return entities.get(0);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object searchUniqueName(final int transform, final java.lang.String name)
    {
        final bw.co.sigmaproduce.crop.type.CropType entity=this.searchUniqueName(name);
        if(entity == null)
        {
            return null;
        }
        return transformEntity(transform, entity);
    }


    /**
     * Create or Update the <code>cropType</code> instance in the persistent store.
     * @param cropType
     */
    @Override
    public bw.co.sigmaproduce.crop.type.CropType createOrUpdate(bw.co.sigmaproduce.crop.type.CropType cropType)
    {
        if(cropType.getId() == null)
        {
            return (bw.co.sigmaproduce.crop.type.CropType)this.create(TRANSFORM_NONE,cropType);
        }
        this.update(cropType);
        return cropType;
    }

    // spring-hibernate-dao-base merge-point
}
