// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.sigmaproduce.document.type;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.sigmaproduce.AuditTracker;

@RestController
@Tag(name = "Document Type", description = "Managing document types.")
public class DocumentTypeApiImpl implements DocumentTypeApi {
        protected final DocumentTypeService documentTypeService;
    
    public DocumentTypeApiImpl(
        DocumentTypeService documentTypeService    ) {
        
        this.documentTypeService = documentTypeService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<DocumentTypeDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<DocumentTypeDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<DocumentTypeDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<DocumentTypeDTO>> pagedSearch(String criteria, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.search(criteria, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<DocumentTypeDTO> save(DocumentTypeDTO documentType) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(documentType, authentication);

            return ResponseEntity.ok(documentTypeService.save(documentType));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<DocumentTypeDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(documentTypeService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return documentTypeService
     */
    protected DocumentTypeService getDocumentTypeService()
    {
        return this.documentTypeService;
    }
}