// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.document.type;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
)
public interface DocumentTypeMapper {
    
    /**
     * Converts this entity to an object of type {@link DocumentTypeDTO}.
     * @param entity
     * @return DocumentTypeDTO
     */
    DocumentTypeDTO toDocumentTypeDTO(DocumentType entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link DocumentTypeDTO}.
     * @param entities
     * @return Collection<DocumentTypeDTO>     */
    List<DocumentTypeDTO> toDocumentTypeDTOCollection(Collection<DocumentType> entities);

    /**
     * Converts an instance of type {@link DocumentTypeDTO} to this DAO's entity.
     * @param documentTypeDTO
     * @return DocumentType
     */
    @InheritInverseConfiguration
    DocumentType documentTypeDTOToEntity(DocumentTypeDTO documentTypeDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateDocumentTypeFromDocumentTypeDTO(DocumentTypeDTO documentTypeDTO, @MappingTarget DocumentType entity);

}