// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 06/12/2024 19:31:13+0200.
//
package bw.co.sigmaproduce.farm.cultivation;

/**
 * @see Cultivation
 */
// HibernateEntityImpl.vsl annotations merge-point
public class CultivationImpl
    extends Cultivation
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 485724126903068222L;

// HibernateEntityImpl.vsl merge-point
}