// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 06/12/2024 19:31:21+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.sigmaproduce::farm::cultivation::CultivationService
 * STEREOTYPE:   Service
 */
package bw.co.sigmaproduce.farm.cultivation;

import java.util.Collection;
import org.springframework.data.domain.Page;

/**
 * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService
 */
public interface CultivationService
{
    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.findById
     * @param id TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.findById(id)
     * @return CultivationVO
     */
    public CultivationVO findById(String id);

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.getAll
     * @return Collection<CultivationListVO>
     */
    public Collection<CultivationListVO> getAll();

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.remove
     * @param id TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.remove(id)
     * @return boolean
     */
    public boolean remove(String id);

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.save
     * @param cultivation TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.save(cultivation)
     * @return CultivationVO
     */
    public CultivationVO save(CultivationVO cultivation);

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.search
     * @param criteria TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.search(criteria)
     * @return Collection<CultivationListVO>
     */
    public Collection<CultivationListVO> search(CultivationCriteria criteria);

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.search
     * @param pageNumber TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.search(pageNumber)
     * @param pageSize TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.search(pageSize)
     * @param criteria TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.search(criteria)
     * @return Page<CultivationListVO>
     */
    public Page<CultivationListVO> search(Integer pageNumber, Integer pageSize, CultivationCriteria criteria);

    /**
     * TODO: Model Documentation for bw.co.sigmaproduce.farm.cultivation.CultivationService.getAll
     * @param pageNumber TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.getAll(pageNumber)
     * @param pageSize TODO: Model Documentation for
bw.co.sigmaproduce.farm.cultivation.CultivationService.getAll(pageSize)
     * @return Page<CultivationListVO>
     */
    public Page<CultivationListVO> getAll(Integer pageNumber, Integer pageSize);

}