// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.farm.cultivation;

import bw.co.sigmaproduce.crop.variety.CropVarietyMapper;
import bw.co.sigmaproduce.farm.FarmMapper;
import bw.co.sigmaproduce.farm.cultivation.harvest.HarvestMapper;
import bw.co.sigmaproduce.farm.cultivation.problem.CultivationProblemMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        FarmMapper.class,
        CropVarietyMapper.class,
        HarvestMapper.class,
        CultivationProblemMapper.class    }
)
public interface CultivationMapper {
    
    /**
     * Converts this entity to an object of type {@link CultivationDTO}.
     * @param entity
     * @return CultivationDTO
     */
    // WARNING! No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    // WARNING! No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    @Mapping(source = "farm", target = "farm")
    @Mapping(source = "cropVariety", target = "cropVariety")
    // WARNING! No conversion for target.cultivationDate (can't convert source.getCultivationDate():java.util.Date to java.util.Date
    // WARNING! No conversion for target.exptectedHarvestDate (can't convert source.getExptectedHarvestDate():java.util.Date to java.util.Date
    CultivationDTO toCultivationDTO(Cultivation entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link CultivationDTO}.
     * @param entities
     * @return Collection<CultivationDTO>     */
    List<CultivationDTO> toCultivationDTOCollection(Collection<Cultivation> entities);

    /**
     * Converts an instance of type {@link CultivationDTO} to this DAO's entity.
     * @param cultivationDTO
     * @return Cultivation
     */
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    // No conversion for target.cultivationDate (can't convert source.getCultivationDate():java.util.Date to java.util.Date
    // No conversion for target.exptectedHarvestDate (can't convert source.getExptectedHarvestDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    Cultivation cultivationDTOToEntity(CultivationDTO cultivationDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    // No conversion for target.cultivationDate (can't convert source.getCultivationDate():java.util.Date to java.util.Date
    // No conversion for target.exptectedHarvestDate (can't convert source.getExptectedHarvestDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    void updateCultivationFromCultivationDTO(CultivationDTO cultivationDTO, @MappingTarget Cultivation entity);

    /**
     * Converts this entity to an object of type {@link CultivationListDTO}.
     * @param entity
     * @return CultivationListDTO
     */
    // WARNING! No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    // WARNING! No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // WARNING! No conversion for target.cropVariety (can't convert source.getCropVariety():bw.co.sigmaproduce.crop.variety.CropVariety to java.lang.String
    // WARNING! No conversion for target.farm (can't convert source.getFarm():bw.co.sigmaproduce.farm.Farm to java.lang.String
    @Mapping(source = "farm.name", target = "farm")
    @Mapping(source = "cropVariety.name", target = "cropVariety")
    CultivationListDTO toCultivationListDTO(Cultivation entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link CultivationListDTO}.
     * @param entities
     * @return Collection<CultivationListDTO>     */
    List<CultivationListDTO> toCultivationListDTOCollection(Collection<Cultivation> entities);

    /**
     * Converts an instance of type {@link CultivationListDTO} to this DAO's entity.
     * @param cultivationListDTO
     * @return Cultivation
     */
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    Cultivation cultivationListDTOToEntity(CultivationListDTO cultivationListDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    void updateCultivationFromCultivationListDTO(CultivationListDTO cultivationListDTO, @MappingTarget Cultivation entity);

}