// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { CropTypeViewComponent } from '@views/crop/type/crop-type-view/crop-type-view';
import { CropTypeViewVarsForm } from '@views/crop/type/crop-type-view/crop-type-view';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { CropTypeDetailsImplComponent } from '@components/crop/type/crop-type-details-impl';
import { CropTypeEditorImplComponent } from '@components/crop/type/crop-type-editor-impl';

@Component({
  selector: 'app-crop-type-view',
  templateUrl: './crop-type-view.html',
  styleUrls: ['./crop-type-view.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    CropTypeDetailsImplComponent,
    CropTypeEditorImplComponent,
  ],
})
export class CropTypeViewImplComponent extends CropTypeViewComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}