// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by hibernate/HibernateEntity.vsl in andromda-hibernate-cartridge on 06/12/2024 19:31:12+0200.
//
package bw.co.sigmaproduce.crop;

import bw.co.sigmaproduce.TimePeriod;
import bw.co.sigmaproduce.crop.issue.CropIssue;
import bw.co.sigmaproduce.crop.type.CropType;
import bw.co.sigmaproduce.crop.variety.CropVariety;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.Lob;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.io.File;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.HashSet;

/**
 * TODO: Model Documentation for Crop
 */
@Entity
@Table(name = "CROP")
// Uncomment to enable caching for Crop
// @org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.read-write)
@NamedQuery(name = "Crop.findAll", query = "SELECT c FROM Crop AS c")
// HibernateEntity.vsl annotations merge-point
public class Crop
    implements Serializable, Comparable<Crop>
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1727720906830403894L;

    // Generate 10 attributes
    private String id;

    /**
     * TODO: Model Documentation for Crop.id
     * @return this.id String
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "ID", unique = false, nullable = true, insertable = true, updatable = true)
    public String getId()
    {
        return this.id;
    }

    /**
     * TODO: Model Documentation for Crop.id
     * @param idIn String
     */
    public void setId(String idIn)
    {
        this.id = idIn;
    }

    private String createdBy;

    /**
     * TODO: Model Documentation for Crop.createdBy
     * @return this.createdBy String
     */
    @Column(name = "CREATED_BY", unique = false, nullable = false, insertable = true, updatable = true)
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    /**
     * TODO: Model Documentation for Crop.createdBy
     * @param createdByIn String
     */
    public void setCreatedBy(String createdByIn)
    {
        this.createdBy = createdByIn;
    }

    private String updatedBy;

    /**
     * TODO: Model Documentation for Crop.updatedBy
     * @return this.updatedBy String
     */
    @Column(name = "UPDATED_BY", unique = false, nullable = true, insertable = true, updatable = true)
    public String getUpdatedBy()
    {
        return this.updatedBy;
    }

    /**
     * TODO: Model Documentation for Crop.updatedBy
     * @param updatedByIn String
     */
    public void setUpdatedBy(String updatedByIn)
    {
        this.updatedBy = updatedByIn;
    }

    private LocalDateTime updatedDate;

    /**
     * TODO: Model Documentation for Crop.updatedDate
     * @return this.updatedDate LocalDateTime
     */
    @Column(name = "UPDATED_DATE", unique = false, nullable = true, insertable = true, updatable = true)
    public LocalDateTime getUpdatedDate()
    {
        return this.updatedDate;
    }

    /**
     * TODO: Model Documentation for Crop.updatedDate
     * @param updatedDateIn LocalDateTime
     */
    public void setUpdatedDate(LocalDateTime updatedDateIn)
    {
        this.updatedDate = updatedDateIn;
    }

    private LocalDateTime createdDate;

    /**
     * TODO: Model Documentation for Crop.createdDate
     * @return this.createdDate LocalDateTime
     */
    @Column(name = "CREATED_DATE", unique = false, nullable = false, insertable = true, updatable = true)
    public LocalDateTime getCreatedDate()
    {
        return this.createdDate;
    }

    /**
     * TODO: Model Documentation for Crop.createdDate
     * @param createdDateIn LocalDateTime
     */
    public void setCreatedDate(LocalDateTime createdDateIn)
    {
        this.createdDate = createdDateIn;
    }

    private String name;

    /**
     * TODO: Model Documentation for Crop.name
     * @return this.name String
     */
    @Column(name = "NAME", unique = true, nullable = false, insertable = true, updatable = true)
    public String getName()
    {
        return this.name;
    }

    /**
     * TODO: Model Documentation for Crop.name
     * @param nameIn String
     */
    public void setName(String nameIn)
    {
        this.name = nameIn;
    }

    private String code;

    /**
     * TODO: Model Documentation for Crop.code
     * @return this.code String
     */
    @Column(name = "CODE", unique = true, nullable = false, insertable = true, updatable = true)
    public String getCode()
    {
        return this.code;
    }

    /**
     * TODO: Model Documentation for Crop.code
     * @param codeIn String
     */
    public void setCode(String codeIn)
    {
        this.code = codeIn;
    }

    private Collection<File> images;

    /**
     * TODO: Model Documentation for Crop.images
     * @return this.images Collection<File>
     */
    @ElementCollection
    public Collection<File> getImages()
    {
        return this.images;
    }

    /**
     * TODO: Model Documentation for Crop.images
     * @param imagesIn Collection<File>
     */
    public void setImages(Collection<File> imagesIn)
    {
        this.images = imagesIn;
    }

    private String description;

    /**
     * TODO: Model Documentation for Crop.description
     * @return this.description String
     */
    @Lob
    @Column(name = "DESCRIPTION", unique = false, nullable = true, insertable = true, updatable = true)
    public String getDescription()
    {
        return this.description;
    }

    /**
     * TODO: Model Documentation for Crop.description
     * @param descriptionIn String
     */
    public void setDescription(String descriptionIn)
    {
        this.description = descriptionIn;
    }

    private TimePeriod maturesIn;

    /**
     * TODO: Model Documentation for Crop.maturesIn
     * @return this.maturesIn TimePeriod
     */
    @Column(name = "MATURES_IN", unique = false, nullable = true, insertable = true, updatable = true)
    @Enumerated(EnumType.STRING)
    public TimePeriod getMaturesIn()
    {
        return this.maturesIn;
    }

    /**
     * TODO: Model Documentation for Crop.maturesIn
     * @param maturesInIn TimePeriod
     */
    public void setMaturesIn(TimePeriod maturesInIn)
    {
        this.maturesIn = maturesInIn;
    }

    // Generate 3 associations
    private Collection<CropVariety> cropVarieties = new HashSet<CropVariety>();

    /**
     * TODO: Model Documentation for CropVariety
     * @return this.cropVarieties Collection<CropVariety>
     */
    @OneToMany(cascade = {CascadeType.PERSIST} , mappedBy = "crop") 
    public Collection<CropVariety> getCropVarieties()
    {
        return this.cropVarieties;
    }

    /**
     * TODO: Model Documentation for CropVariety
     * @param cropVarietiesIn Collection<CropVariety>
     */
    public void setCropVarieties(Collection<CropVariety> cropVarietiesIn)
    {
        this.cropVarieties = cropVarietiesIn;
    }

    /**
     * TODO: Model Documentation for CropVariety
     * @param elementToAdd CropVariety
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addCropVarieties(CropVariety elementToAdd)
    {
        return this.cropVarieties.add(elementToAdd);
    }

    /**
     * TODO: Model Documentation for CropVariety
     * @param elementToRemove CropVariety
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeCropVarieties(CropVariety elementToRemove)
    {
        return this.cropVarieties.remove(elementToRemove);
    }

    private CropType type;

    /**
     * TODO: Model Documentation for CropType
     * @return this.type CropType
     */
    @ManyToOne( fetch = FetchType.LAZY)
    @JoinColumn(name = "TYPE_FK")
    public CropType getType()
    {
        return this.type;
    }

    /**
     * TODO: Model Documentation for CropType
     * @param typeIn CropType
     */
    public void setType(CropType typeIn)
    {
        this.type = typeIn;
    }

    private Collection<CropIssue> issues = new HashSet<CropIssue>();

    /**
     * TODO: Model Documentation for CropIssue
     * @return this.issues Collection<CropIssue>
     */
    @ManyToMany()
    @JoinTable
    (
        name = "CROPS2ISSUES",
        joinColumns = {@JoinColumn(name = "CROPS_FK")},
        inverseJoinColumns = {@JoinColumn(name = "ISSUES_FK")}
    )
    public Collection<CropIssue> getIssues()
    {
        return this.issues;
    }

    /**
     * TODO: Model Documentation for CropIssue
     * @param issuesIn Collection<CropIssue>
     */
    public void setIssues(Collection<CropIssue> issuesIn)
    {
        this.issues = issuesIn;
    }

    /**
     * TODO: Model Documentation for CropIssue
     * @param elementToAdd CropIssue
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean addIssues(CropIssue elementToAdd)
    {
        return this.issues.add(elementToAdd);
    }

    /**
     * TODO: Model Documentation for CropIssue
     * @param elementToRemove CropIssue
     * @return <tt>true</tt> if this collection changed as a result of the
     *         call
     */
    public boolean removeIssues(CropIssue elementToRemove)
    {
        return this.issues.remove(elementToRemove);
    }

    /**
     * Returns <code>true</code> if the argument is an Crop instance and all identifiers for this entity
     * equal the identifiers of the argument entity. Returns <code>false</code> otherwise.
     */
    @Override
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Crop))
        {
            return false;
        }
        final Crop that = (Crop)object;
        if (this.id == null || that.getId() == null || !this.id.equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code based on this entity's identifiers.
     */
    @Override
    public int hashCode()
    {
        int hashCode = 0;
        hashCode = 29 * hashCode + (this.id == null ? 0 : this.id.hashCode());

        return hashCode;
    }

    /**
     * Constructs new instances of {@link Crop}.
     */
    public static final class Factory
    {
        /**
         * Constructs a new instance of {@link Crop}.
         * @return new Crop()
         */
        public static Crop newInstance()
        {
            return new Crop();
        }

        /**
         * Constructs a new instance of {@link Crop}, taking all required and/or
         * read-only properties as arguments, except for identifiers.
         * @param createdBy String
         * @param createdDate LocalDateTime
         * @param name String
         * @param code String
         * @return newInstance
         */
        public static Crop newInstance(String createdBy, LocalDateTime createdDate, String name, String code)
        {
            final Crop entity = new Crop();
            entity.setCreatedBy(createdBy);
            entity.setCreatedDate(createdDate);
            entity.setName(name);
            entity.setCode(code);
            return entity;
        }

        /**
         * Constructs a new instance of {@link Crop}, taking all possible properties
         * (except the identifier(s))as arguments.
         * @param createdBy String
         * @param updatedBy String
         * @param updatedDate LocalDateTime
         * @param createdDate LocalDateTime
         * @param name String
         * @param code String
         * @param images Collection<File>
         * @param description String
         * @param maturesIn TimePeriod
         * @param cropVarieties Collection<CropVariety>
         * @param type CropType
         * @param issues Collection<CropIssue>
         * @return newInstance Crop
         */
        public static Crop newInstance(String createdBy, String updatedBy, LocalDateTime updatedDate, LocalDateTime createdDate, String name, String code, Collection<File> images, String description, TimePeriod maturesIn, Collection<CropVariety> cropVarieties, CropType type, Collection<CropIssue> issues)
        {
            final Crop entity = new Crop();
            entity.setCreatedBy(createdBy);
            entity.setUpdatedBy(updatedBy);
            entity.setUpdatedDate(updatedDate);
            entity.setCreatedDate(createdDate);
            entity.setName(name);
            entity.setCode(code);
            entity.setImages(images);
            entity.setDescription(description);
            entity.setMaturesIn(maturesIn);
            entity.setCropVarieties(cropVarieties);
            entity.setType(type);
            entity.setIssues(issues);
            return entity;
        }
    }

    /**
     * @param other
     * @return a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object.
     * @see Comparable#compareTo
     */
    @Override
    public int compareTo(Crop other)
    {
        int cmp = 0;
        if (this.getId() != null)
        {
            cmp = this.getId().compareTo(other.getId());
        }
        else
        {
            if (this.getCreatedBy() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getCreatedBy().compareTo(other.getCreatedBy()));
            }
            if (this.getUpdatedBy() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getUpdatedBy().compareTo(other.getUpdatedBy()));
            }
            if (this.getUpdatedDate() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getUpdatedDate().compareTo(other.getUpdatedDate()));
            }
            if (this.getCreatedDate() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getCreatedDate().compareTo(other.getCreatedDate()));
            }
            if (this.getName() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getName().compareTo(other.getName()));
            }
            if (this.getCode() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getCode().compareTo(other.getCode()));
            }
            if (this.getImages() != null)
            {
                // Compare Collection sizes for ordering
                cmp = (cmp != 0 ? cmp : Math.abs(this.getImages().size()-other.getImages().size()));
            }
            if (this.getDescription() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getDescription().compareTo(other.getDescription()));
            }
            if (this.getMaturesIn() != null)
            {
                cmp = (cmp != 0 ? cmp : this.getMaturesIn().compareTo(other.getMaturesIn()));
            }
        }
        return cmp;
    }

    /**
     * Returns a String representation of the object
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     * @see Object#toString
     */
    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("Crop(");
        sb.append(" id=").append(getId());
        sb.append(" createdBy=").append(getCreatedBy());
        sb.append(" updatedBy=").append(getUpdatedBy());
        sb.append(" updatedDate=").append(getUpdatedDate());
        sb.append(" createdDate=").append(getCreatedDate());
        sb.append(" name=").append(getName());
        sb.append(" code=").append(getCode());
        sb.append(" images=").append(getImages());
        sb.append(" description=").append(getDescription());
        sb.append(" maturesIn=").append(getMaturesIn());
        sb.append(")");
        return sb.toString();
    }
// HibernateEntity.vsl merge-point
}