// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.sigmaproduce.owner;

import io.swagger.v3.oas.annotations.Operation;
import java.util.Collection;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class OwnerApiImpl implements OwnerApi {
        protected final OwnerService ownerService;
    
    public OwnerApiImpl(
        OwnerService ownerService    ) {
        
        this.ownerService = ownerService;
    }



    @Override
    @Operation(summary = "Find Crop by id", description = "Get the cropp with the given id")
    public ResponseEntity<OwnerDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Get Crops", description = "Get all all crops in the data store")
    public ResponseEntity<Collection<OwnerListDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Remove crop by id", description = "Remove the crop with the given id")
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Save Crop", description = "Save acrops to data store")
    public ResponseEntity<OwnerDTO> save(OwnerDTO owner) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Search Crops", description = "Search crops based on the criteria")
    public ResponseEntity<Collection<OwnerListDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return ownerService
     */
    protected OwnerService getOwnerService()
    {
        return this.ownerService;
    }
}