// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Inject } from '@angular/core';
import { EditHarvestComponent } from '@views/farm/edit-harvest/edit-harvest';
import { EditHarvestVarsForm } from '@views/farm/edit-harvest/edit-harvest';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { HarvestEditorImplComponent } from '@components/farm/cultivation/harvest/harvest-editor-impl';

@Component({
  selector: 'app-edit-harvest',
  templateUrl: './edit-harvest.html',
  styleUrls: ['./edit-harvest.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    HarvestEditorImplComponent,
  ],
})
export class EditHarvestImplComponent extends EditHarvestComponent {

    constructor(@Inject(MAT_DIALOG_DATA) data: any) {
        super(data);
    }

    doNgOnDestroy(): void {
    }
}