// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Inject } from '@angular/core';
import { EditPostComponent } from '@views/farm/edit-post/edit-post';
import { EditPostVarsForm } from '@views/farm/edit-post/edit-post';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { PostEditorImplComponent } from '@components/farm/post/post-editor-impl';

@Component({
  selector: 'app-edit-post',
  templateUrl: './edit-post.html',
  styleUrls: ['./edit-post.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    PostEditorImplComponent,
  ],
})
export class EditPostImplComponent extends EditPostComponent {

    constructor(@Inject(MAT_DIALOG_DATA) data: any) {
        super(data);
    }

    doNgOnDestroy(): void {
    }
}