// license-header java merge-point ===>
//
// Attention: Generated code! Do not modify by hand!
// Generated by hibernate/SearchCriteria.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.auth;

import java.io.Serializable;
import java.util.Collection;

/**
 * TODO: Model Documentation for AuthorisationCriteria
 */
public class AuthorisationCriteria
    implements Serializable
{

    /**
     * TODO: Model Documentation for AuthorisationCriteria
     */
    public AuthorisationCriteria()
    {
        // Empty default constructor
    }

    /**
     * Constructor taking all properties.
     */
    public AuthorisationCriteria(
        String accessPointName,
        String accessPointUrl,
        Collection<String> roles)

    {
        this.accessPointName = accessPointName;
        this.accessPointUrl = accessPointUrl;
        this.roles = roles;
    }

    /**
     * Copies constructor from other AuthorisationCriteria
     */
    public AuthorisationCriteria(AuthorisationCriteria otherBean)
    {
        if (otherBean != null)
        {
            this.accessPointName = otherBean.getAccessPointName();
            this.accessPointUrl = otherBean.getAccessPointUrl();
            this.roles = otherBean.getRoles();
        }
    }

    /**
     * The first result to retrieve.
     */
    private Integer firstResult;

    /**
     * Gets the first result to retrieve.
     *
     * @return the first result to retrieve
     */
    public Integer getFirstResult()
    {
        return this.firstResult;
    }

    /**
     * Sets the first result to retrieve.
     *
     * @param firstResult the first result to retrieve
     */
    public void setFirstResult(Integer firstResult)
    {
        this.firstResult = firstResult;
    }

    /**
     * The fetch size.
     */
    private Integer fetchSize = 0;

    /**
     * Gets the fetch size.
     *
     * @return the fetch size
     */
    public Integer getFetchSize()
    {
        return this.fetchSize;
    }

    /**
     * Sets the fetch size.
     *
     * @param fetchSize the fetch size
     */
    public void setFetchSize(Integer fetchSize)
    {
        this.fetchSize = fetchSize;
    }

    /**
     * The maximum size of the result set.
     */
    private Integer maximumResultSize;

    /**
     * Gets the maximum size of the search result.
     *
     * @return the maximum size of the search result.
     */
    public Integer getMaximumResultSize()
    {
        return this.maximumResultSize;
    }

    /**
     * Sets the maxmimum size of the result.
     *
     * @param maximumResultSize A number indicating how many results will be returned.
     */
    public void setMaximumResultSize(Integer maximumResultSize)
    {
        this.maximumResultSize = maximumResultSize;
    }

    /**
     * The page number of the result set.
     */
    private Integer pageNumber = -1;

    /**
     * Gets the page number of the search result.
     *
     * @return the page number of the search result.
     */
    public Integer getPageNumber()
    {
        return this.pageNumber;
    }

    /**
     * Sets the page number of the result.
     *
     * @param pageNumber A number indicating how many results will be returned.
     */
    public void setPageNumber(Integer pageNumber)
    {
        this.pageNumber = pageNumber;
    }

    private String accessPointName;

    /**
     * TODO: Model Documentation for AuthorisationCriteria.accessPointName
     */
    public String getAccessPointName()
    {
        return this.accessPointName;
    }

    public void setAccessPointName(String accessPointName)
    {
        this.accessPointName = accessPointName;
    }

    private String accessPointUrl;

    /**
     * TODO: Model Documentation for AuthorisationCriteria.accessPointUrl
     */
    public String getAccessPointUrl()
    {
        return this.accessPointUrl;
    }

    public void setAccessPointUrl(String accessPointUrl)
    {
        this.accessPointUrl = accessPointUrl;
    }

    private Collection<String> roles;

    /**
     * TODO: Model Documentation for AuthorisationCriteria.roles
     */
    public Collection<String> getRoles()
    {
        return this.roles;
    }

    public void setRoles(Collection<String> roles)
    {
        this.roles = roles;
    }

}