// license-header java merge-point
//
/**
 * @author Generated by Service.vsl in andromda-java-cartridge on 05/31/2024 22:50:45+0200 Do not modify by hand!
 *
 * TEMPLATE:     Service.vsl in andromda-java-cartridge.
 * MODEL CLASS:  bocraportal::backend::bw.co.sigmaproduce::access::AccessPointService
 * STEREOTYPE:   Service
 */
package bw.co.sigmaproduce.access;

import java.util.Collection;

import org.springframework.data.domain.Page;

/**
 * TODO: Model Documentation for AccessPointService
 */
public interface AccessPointService
{
    /**
     * TODO: Model Documentation for AccessPointService.findById
     * @param id TODO: Model Documentation for AccessPointService.findById(id)
     * @return AccessPointVO
     */
    public AccessPointVO findById(Long id);

    /**
     * TODO: Model Documentation for AccessPointService.getAll
     * @return Collection<AccessPointVO>
     */
    public Collection<AccessPointVO> getAll();

    /**
     * TODO: Model Documentation for AccessPointService.getAll
     * @param pageNumber TODO: Model Documentation for AccessPointService.getAll(pageNumber)
     * @param pageSize TODO: Model Documentation for AccessPointService.getAll(pageSize)
     * @return Collection<AccessPointVO>
     */
    public Collection<AccessPointVO> getAll(Integer pageNumber, Integer pageSize);

    /**
     * TODO: Model Documentation for AccessPointService.remove
     * @param id TODO: Model Documentation for AccessPointService.remove(id)
     * @return boolean
     */
    public boolean remove(Long id);

    /**
     * TODO: Model Documentation for AccessPointService.save
     * @param accessPoint TODO: Model Documentation for AccessPointService.save(accessPoint)
     * @return AccessPointVO
     */
    public AccessPointVO save(AccessPointVO accessPoint);

    /**
     * TODO: Model Documentation for AccessPointService.search
     * @param criteria TODO: Model Documentation for AccessPointService.search(criteria)
     * @return Collection<AccessPointVO>
     */
    public Collection<AccessPointVO> search(AccessPointCriteria criteria);

    /**
     * TODO: Model Documentation for AccessPointService.search
     * @param pageNumber TODO: Model Documentation for AccessPointService.search(pageNumber)
     * @param pageSize TODO: Model Documentation for AccessPointService.search(pageSize)
     * @param criteria TODO: Model Documentation for AccessPointService.search(criteria)
     * @return DataPage
     */
    public Page<AccessPointVO> search(Integer pageNumber, Integer pageSize, AccessPointCriteria criteria);

}