// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { FarmViewComponent } from '@views/farm/details/farm-view';
import { FarmViewVarsForm } from '@views/farm/details/farm-view';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { FarmDetailsImplComponent } from '@components/farm/farm-details-impl';

@Component({
  selector: 'app-farm-view',
  templateUrl: './farm-view.html',
  styleUrls: ['./farm-view.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    FarmDetailsImplComponent,
  ],
})
export class FarmViewImplComponent extends FarmViewComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}