// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.sigmaproduce.district;

import io.swagger.v3.oas.annotations.Operation;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * 
 * TODO: Model Documentation for bw.co.sigmaproduce.district.DistrictApi
 */
public interface DistrictApi {

    @GetMapping("/{id}")
    @Operation(summary = "Find District by id", description = "Get the district with the given id")
    public ResponseEntity<?> findById(@PathVariable(name = "id", required = false) Long id);

    @GetMapping()
    @Operation(summary = "Get All Districts", description = "Get all districts in the data store")
    public ResponseEntity<?> getAll();

    @DeleteMapping("/{id}")
    @Operation(summary = "Remove crop by id", description = "Remove the district with the given id")
    public ResponseEntity<?> remove(@PathVariable(name = "id", required = false) Long id);

    @PostMapping()
    @Operation(summary = "Save District", description = "Save district to data store")
    public ResponseEntity<?> save(@RequestBody(required = true) DistrictVO district);

    @GetMapping("search")
    @Operation(summary = "Search Districts", description = "Search district based on the criteria")
    public ResponseEntity<?> search(@RequestParam(name = "criteria", required = false) String criteria);
}