// license-header java merge-point
//
/**
 * @author Generated by ValueObject.vsl in andromda-java-cartridge on 06/12/2024 19:31:22+0200 Do not modify by hand!
 *
 * TEMPLATE:     ValueObject.vsl in andromda-java-cartridge.
 * MODEL CLASS:  AndroMDAModel::backend::bw.co.sigmaproduce::farm::cultivation::problem::CultivationProblemVO
 * STEREOTYPE:   ValueObject
 */
package bw.co.sigmaproduce.farm.cultivation.problem;

import bw.co.sigmaproduce.crop.issue.CropIssueVO;
import bw.co.sigmaproduce.farm.cultivation.CultivationListVO;
import java.io.File;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * TODO: Model Documentation for CultivationProblemVO
 */
public class CultivationProblemVO
    implements Serializable, Comparable<CultivationProblemVO>
{
    /** The serial version UID of this class. Needed for serialization. */
    private static final long serialVersionUID = -5961175232833071311L;

    // Class attributes
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.id
     */
    protected String id;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdBy
     */
    protected String createdBy;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedBy
     */
    protected String updatedBy;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdDate
     */
    protected LocalDateTime createdDate;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedDate
     */
    protected LocalDateTime updatedDate;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cropIssue
     */
    protected CropIssueVO cropIssue;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cultivation
     */
    protected CultivationListVO cultivation;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.description
     */
    protected String description;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.photos
     */
    protected Collection<File> photos;
    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.dateNoticed
     */
    protected LocalDate dateNoticed;

    /** Default Constructor with no properties */
    public CultivationProblemVO()
    {
        // Documented empty block - avoid compiler warning - no super constructor
    }

    /**
     * Constructor taking only required properties
     * @param cropIssueIn CropIssueVO TODO: Model Documentation for
CultivationProblemVO.cropIssue
     * @param cultivationIn CultivationListVO TODO: Model Documentation for
CultivationProblemVO.cultivation
     * @param descriptionIn String TODO: Model Documentation for
CultivationProblemVO.description
     * @param dateNoticedIn LocalDate TODO: Model Documentation for
CultivationProblemVO.dateNoticed
     */
    public CultivationProblemVO(final CropIssueVO cropIssueIn, final CultivationListVO cultivationIn, final String descriptionIn, final LocalDate dateNoticedIn)
    {
        this.cropIssue = cropIssueIn;
        this.cultivation = cultivationIn;
        this.description = descriptionIn;
        this.dateNoticed = dateNoticedIn;
    }

    /**
     * Constructor with all properties
     * @param idIn String
     * @param createdByIn String
     * @param updatedByIn String
     * @param createdDateIn LocalDateTime
     * @param updatedDateIn LocalDateTime
     * @param cropIssueIn CropIssueVO
     * @param cultivationIn CultivationListVO
     * @param descriptionIn String
     * @param photosIn Collection<File>
     * @param dateNoticedIn LocalDate
     */
    public CultivationProblemVO(final String idIn, final String createdByIn, final String updatedByIn, final LocalDateTime createdDateIn, final LocalDateTime updatedDateIn, final CropIssueVO cropIssueIn, final CultivationListVO cultivationIn, final String descriptionIn, final Collection<File> photosIn, final LocalDate dateNoticedIn)
    {
        this.id = idIn;
        this.createdBy = createdByIn;
        this.updatedBy = updatedByIn;
        this.createdDate = createdDateIn;
        this.updatedDate = updatedDateIn;
        this.cropIssue = cropIssueIn;
        this.cultivation = cultivationIn;
        this.description = descriptionIn;
        this.photos = photosIn;
        this.dateNoticed = dateNoticedIn;
    }

    /**
     * Copies constructor from other CultivationProblemVO
     *
     * @param otherBean Cannot be <code>null</code>
     * @throws NullPointerException if the argument is <code>null</code>
     */
    public CultivationProblemVO(final CultivationProblemVO otherBean)
    {
        this.id = otherBean.getId();
        this.createdBy = otherBean.getCreatedBy();
        this.updatedBy = otherBean.getUpdatedBy();
        this.createdDate = otherBean.getCreatedDate();
        this.updatedDate = otherBean.getUpdatedDate();
        this.cropIssue = otherBean.getCropIssue();
        this.cultivation = otherBean.getCultivation();
        this.description = otherBean.getDescription();
        this.photos = otherBean.getPhotos();
        this.dateNoticed = otherBean.getDateNoticed();
    }

    /**
     * Copies all properties from the argument value object into this value object.
     * @param otherBean Cannot be <code>null</code>
     */
    public void copy(final CultivationProblemVO otherBean)
    {
        if (null != otherBean)
        {
            this.setId(otherBean.getId());
            this.setCreatedBy(otherBean.getCreatedBy());
            this.setUpdatedBy(otherBean.getUpdatedBy());
            this.setCreatedDate(otherBean.getCreatedDate());
            this.setUpdatedDate(otherBean.getUpdatedDate());
            this.setCropIssue(otherBean.getCropIssue());
            this.setCultivation(otherBean.getCultivation());
            this.setDescription(otherBean.getDescription());
            this.setPhotos(otherBean.getPhotos());
            this.setDateNoticed(otherBean.getDateNoticed());
        }
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.id
     * Get the id Attribute
     * @return id String
     */
    public String getId()
    {
        return this.id;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.id
     * @param value String
     */
    public void setId(final String value)
    {
        this.id = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdBy
     * Get the createdBy Attribute
     * @return createdBy String
     */
    public String getCreatedBy()
    {
        return this.createdBy;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdBy
     * @param value String
     */
    public void setCreatedBy(final String value)
    {
        this.createdBy = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedBy
     * Get the updatedBy Attribute
     * @return updatedBy String
     */
    public String getUpdatedBy()
    {
        return this.updatedBy;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedBy
     * @param value String
     */
    public void setUpdatedBy(final String value)
    {
        this.updatedBy = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdDate
     * Get the createdDate Attribute
     * @return createdDate LocalDateTime
     */
    public LocalDateTime getCreatedDate()
    {
        return this.createdDate;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.createdDate
     * @param value LocalDateTime
     */
    public void setCreatedDate(final LocalDateTime value)
    {
        this.createdDate = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedDate
     * Get the updatedDate Attribute
     * @return updatedDate LocalDateTime
     */
    public LocalDateTime getUpdatedDate()
    {
        return this.updatedDate;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.updatedDate
     * @param value LocalDateTime
     */
    public void setUpdatedDate(final LocalDateTime value)
    {
        this.updatedDate = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cropIssue
     * Get the cropIssue Attribute
     * @return cropIssue CropIssueVO
     */
    public CropIssueVO getCropIssue()
    {
        return this.cropIssue;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cropIssue
     * @param value CropIssueVO
     */
    public void setCropIssue(final CropIssueVO value)
    {
        this.cropIssue = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cultivation
     * Get the cultivation Attribute
     * @return cultivation CultivationListVO
     */
    public CultivationListVO getCultivation()
    {
        return this.cultivation;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.cultivation
     * @param value CultivationListVO
     */
    public void setCultivation(final CultivationListVO value)
    {
        this.cultivation = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.description
     * Get the description Attribute
     * @return description String
     */
    public String getDescription()
    {
        return this.description;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.description
     * @param value String
     */
    public void setDescription(final String value)
    {
        this.description = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.photos
     * Get the photos Attribute
     * @return photos Collection<File>
     */
    public Collection<File> getPhotos()
    {
        if (this.photos == null)
        {
            this.photos = new ArrayList<File>();
        }
        return this.photos;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.photos
     * @param value Collection<File>
     */
    public void setPhotos(final Collection<File> value)
    {
        this.photos = value;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.dateNoticed
     * Get the dateNoticed Attribute
     * @return dateNoticed LocalDate
     */
    public LocalDate getDateNoticed()
    {
        return this.dateNoticed;
    }

    /**
     * TODO: Model Documentation for
     * CultivationProblemVO.dateNoticed
     * @param value LocalDate
     */
    public void setDateNoticed(final LocalDate value)
    {
        this.dateNoticed = value;
    }

    /**
     * @param object to compare this object against
     * @return boolean if equal
     * @see Object#equals(Object)
     */
    @Override
    public boolean equals(final Object object)
    {
        if (object==null || object.getClass() != this.getClass())
        {
             return false;
        }
        // Check if the same object instance
        if (object==this)
        {
            return true;
        }
        CultivationProblemVO rhs = (CultivationProblemVO) object;
        return new EqualsBuilder()
            .append(this.getId(), rhs.getId())
            .append(this.getCreatedBy(), rhs.getCreatedBy())
            .append(this.getUpdatedBy(), rhs.getUpdatedBy())
            .append(this.getCreatedDate(), rhs.getCreatedDate())
            .append(this.getUpdatedDate(), rhs.getUpdatedDate())
            .append(this.getCropIssue(), rhs.getCropIssue())
            .append(this.getCultivation(), rhs.getCultivation())
            .append(this.getDescription(), rhs.getDescription())
            .append(this.getPhotos(), rhs.getPhotos())
            .append(this.getDateNoticed(), rhs.getDateNoticed())
            .isEquals();
    }

    /**
     * @param object to compare this object against
     * @return int if equal
     * @see Comparable#compareTo(Object)
     */
    public int compareTo(final CultivationProblemVO object)
    {
        if (object==null)
        {
            return -1;
        }
        // Check if the same object instance
        if (object==this)
        {
            return 0;
        }
        return new CompareToBuilder()
            .append(this.getId(), object.getId())
            .append(this.getCreatedBy(), object.getCreatedBy())
            .append(this.getUpdatedBy(), object.getUpdatedBy())
            .append(this.getCreatedDate(), object.getCreatedDate())
            .append(this.getUpdatedDate(), object.getUpdatedDate())
            .append(this.getCropIssue(), object.getCropIssue())
            .append(this.getCultivation(), object.getCultivation())
            .append(this.getDescription(), object.getDescription())
            .append(this.getPhotos(), object.getPhotos())
            .append(this.getDateNoticed(), object.getDateNoticed())
            .toComparison();
    }

    /**
     * @return int hashCode value
     * @see Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        return new HashCodeBuilder(1249046965, -82296885)
            .append(this.getId())
            .append(this.getCreatedBy())
            .append(this.getUpdatedBy())
            .append(this.getCreatedDate())
            .append(this.getUpdatedDate())
            .append(this.getCropIssue())
            .append(this.getCultivation())
            .append(this.getDescription())
            .append(this.getPhotos())
            .append(this.getDateNoticed())
            .toHashCode();
    }

    /**
     * @return String representation of object
     * @see Object#toString()
     */
    @Override
    public String toString()
    {

        StringBuilder builder = new StringBuilder();
        builder.append("{\n");
        builder.append("\t\"id\" : \"" + this.getId() + "\"");
        builder.append("\t,\"createdBy\" : \"" + this.getCreatedBy() + "\"");
        builder.append("\t,\"updatedBy\" : \"" + this.getUpdatedBy() + "\"");
        builder.append("\t,\"createdDate\" : \"" + this.getCreatedDate() + "\"");
        builder.append("\t,\"updatedDate\" : \"" + this.getUpdatedDate() + "\"");
        builder.append("\t,\"cropIssue\" : \"" + this.getCropIssue() + "\"");
        builder.append("\t,\"cultivation\" : \"" + this.getCultivation() + "\"");
        builder.append("\t,\"description\" : \"" + this.getDescription() + "\"");
        builder.append("\t,\"photos\" : \"" + this.getPhotos() + "\"");
        builder.append("\t,\"dateNoticed\" : \"" + this.getDateNoticed() + "\"");
        builder.append("}");
        return builder.toString();

    }

    /**
     * Compares the properties of this instance to the properties of the argument. This method will return
     * {@code false} as soon as it detects that the argument is {@code null} or not of the same type as
     * (or a sub-type of) this instance's type.
     *
     * <p/>For array, collection or map properties the comparison will be done one level deep, in other words:
     * the elements will be compared using the {@code equals()} operation.
     *
     * <p/>Note that two properties will be considered equal when both values are {@code null}.
     *
     * @param thatObject the object containing the properties to compare against this instance
     * @return this method will return {@code true} in case the argument has the same type as this class, or is a
     *      sub-type of this class and all properties as found on this class have equal values when queried on that
     *      argument instance; in all other cases this method will return {@code false}
     */
    public boolean equalProperties(final Object thatObject)
    {
        if (thatObject == null || !this.getClass().isAssignableFrom(thatObject.getClass()))
        {
            return false;
        }

        final CultivationProblemVO that = (CultivationProblemVO)thatObject;
        return
            equal(this.getId(), that.getId())
            && equal(this.getCreatedBy(), that.getCreatedBy())
            && equal(this.getUpdatedBy(), that.getUpdatedBy())
            && equal(this.getCreatedDate(), that.getCreatedDate())
            && equal(this.getUpdatedDate(), that.getUpdatedDate())
            && equal(this.getCropIssue(), that.getCropIssue())
            && equal(this.getCultivation(), that.getCultivation())
            && equal(this.getDescription(), that.getDescription())
            && equal(this.getPhotos(), that.getPhotos())
            && equal(this.getDateNoticed(), that.getDateNoticed())
        ;
    }

    /**
     * This is a convenient helper method which is able to detect whether or not two values are equal. Two values
     * are equal when they are both {@code null}, are arrays of the same length with equal elements or are
     * equal objects (this includes {@link Collection} and {@link java.util.Map} instances).
     *
     * <p/>Note that for array, collection or map instances the comparison runs one level deep.
     *
     * @param first the first object to compare, may be {@code null}
     * @param second the second object to compare, may be {@code null}
     * @return this method will return {@code true} in case both objects are equal as explained above;
     *      in all other cases this method will return {@code false}
     */
    protected static boolean equal(final Object first, final Object second)
    {
        final boolean equal;

        if (first == null)
        {
            equal = (second == null);
        }
        else if (first.getClass().isArray() && (second != null) && second.getClass().isArray())
        {
            equal = Arrays.equals((Object[])first, (Object[])second);
        }
        else // note that the following also covers Collection and java.util.Map
        {
            equal = first.equals(second);
        }

        return equal;
    }

    // CultivationProblemVO value-object java merge-point
}