// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.sigmaproduce.crop.variety;

import io.swagger.v3.oas.annotations.Operation;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class CropVarietyApiImpl implements CropVarietyApi {
        protected final CropVarietyService cropVarietyService;
    
    public CropVarietyApiImpl(
        CropVarietyService cropVarietyService    ) {
        
        this.cropVarietyService = cropVarietyService;
    }



    @Override
    @Operation(summary = "Find Crop Variety by id", description = "Get the crop variety with the given id")
    public ResponseEntity<CropVarietyDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Get Crop Varieties", description = "Get all all crop varieties in the data store")
    public ResponseEntity<Collection<CropVarietyList>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Get Crop Varieties Page", description = "Get {pageSize} crop varieties with for a particular {pageNumber}")
    public ResponseEntity<Page<CropVarietyList>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Search Crop Varieties Page", description = "Get {pageSize} crop varieties for a particular {pageNumber} given a search criteria")
    public ResponseEntity<Page<CropVarietyList>> pagedSearch(Integer pageNumber, Integer pageSize, String criteria) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.search(pageNumber, pageSize, criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Remove crop variety by id", description = "Remove the crop variety with the given id")
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Save Crop Variety", description = "Save a crop variety to data store")
    public ResponseEntity<CropVarietyDTO> save(CropVarietyDTO cropVariety) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.save(cropVariety));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Search Crop Varieties", description = "Search crop varieties based on the criteria")
    public ResponseEntity<Collection<CropVarietyList>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(cropVarietyService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return cropVarietyService
     */
    protected CropVarietyService getCropVarietyService()
    {
        return this.cropVarietyService;
    }
}