// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.sigmaproduce.crop.variety;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;

public abstract class CropVarietyApiBase implements CropVarietyApi {

    protected Logger logger = LoggerFactory.getLogger(CropVarietyApi.class);
        protected final CropVarietyService cropVarietyService;

    public CropVarietyApiBase(
        CropVarietyService cropVarietyService    ) {
        this.cropVarietyService = cropVarietyService;
    }

    public ResponseEntity<?> findById(String id) {
        return handleFindById(id);
    }

    public abstract ResponseEntity<?> handleFindById(String id);

    public ResponseEntity<?> getAll() {
        return handleGetAll();
    }

    public abstract ResponseEntity<?> handleGetAll();

    public ResponseEntity<?> getAllPaged(Integer pageNumber, Integer pageSize) {
        return handleGetAllPaged(pageNumber, pageSize);
    }

    public abstract ResponseEntity<?> handleGetAllPaged(Integer pageNumber, Integer pageSize);

    public ResponseEntity<?> pagedSearch(Integer pageNumber, Integer pageSize, String criteria) {
        return handlePagedSearch(pageNumber, pageSize, criteria);
    }

    public abstract ResponseEntity<?> handlePagedSearch(Integer pageNumber, Integer pageSize, String criteria);

    public ResponseEntity<?> remove(String id) {
        return handleRemove(id);
    }

    public abstract ResponseEntity<?> handleRemove(String id);

    public ResponseEntity<?> save(CropVarietyVO cropVariety) {
        return handleSave(cropVariety);
    }

    public abstract ResponseEntity<?> handleSave(CropVarietyVO cropVariety);

    public ResponseEntity<?> search(String criteria) {
        return handleSearch(criteria);
    }

    public abstract ResponseEntity<?> handleSearch(String criteria);

    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return cropVarietyService
     */
    protected CropVarietyService getCropVarietyService()
    {
        return this.cropVarietyService;
    }

}