// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWS.java.vsl in andromda-webservices. Do not modify by hand!.
//
package bw.co.sigmaproduce.crop.variety;

import io.swagger.v3.oas.annotations.Operation;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * 
 * TODO: Model Documentation for bw.co.sigmaproduce.crop.variety.CropVarietyApi
 */
public interface CropVarietyApi {

    @GetMapping("/{id}")
    @Operation(summary = "Find Crop Variety by id", description = "Get the crop variety with the given id")
    public ResponseEntity<?> findById(@PathVariable(name = "id", required = true) String id);

    @GetMapping()
    @Operation(summary = "Get Crop Varieties", description = "Get all all crop varieties in the data store")
    public ResponseEntity<?> getAll();

    @GetMapping("/page/{pageNumber}/size/{pageSize}")
    @Operation(summary = "Get Crop Varieties Page", description = "Get {pageSize} crop varieties with for a particular {pageNumber}")
    public ResponseEntity<?> getAllPaged(@PathVariable(name = "pageNumber", required = false) Integer pageNumber, @PathVariable(name = "pageSize", required = false) Integer pageSize);

    @GetMapping("/search/page/{pageNumber}/size/{pageSize}")
    @Operation(summary = "Search Crop Varieties Page", description = "Get {pageSize} crop varieties for a particular {pageNumber} given a search criteria")
    public ResponseEntity<?> pagedSearch(@PathVariable(name = "pageNumber", required = false) Integer pageNumber, @PathVariable(name = "pageSize", required = false) Integer pageSize, @RequestParam(name = "criteria", required = true) String criteria);

    @DeleteMapping("/{id}")
    @Operation(summary = "Remove crop variety by id", description = "Remove the crop variety with the given id")
    public ResponseEntity<?> remove(@PathVariable(name = "id", required = true) String id);

    @PostMapping()
    @Operation(summary = "Save Crop Variety", description = "Save a crop variety to data store")
    public ResponseEntity<?> save(@RequestBody(required = true) CropVarietyVO cropVariety);

    @GetMapping("search")
    @Operation(summary = "Search Crop Varieties", description = "Search crop varieties based on the criteria")
    public ResponseEntity<?> search(@RequestParam(name = "criteria", required = false) String criteria);
}