// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchCropsComponent } from '@app/view/crop/search-crops.component';
import { SearchCropsVarsForm } from '@app/view/crop/search-crops.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";

@Component({
  selector: 'app-search-crops',
  templateUrl: './search-crops.component.html',
  styleUrls: ['./search-crops.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
  ],
})
export class SearchCropsImplComponent extends SearchCropsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchCropsVarsForm): SearchCropsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
