// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.sigmaproduce.farm.cultivation;

import io.swagger.v3.oas.annotations.Operation;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.sigmaproduce.AuditTracker;

@RestController
public class CultivationApiImpl implements CultivationApi {
        protected final CultivationService cultivationService;
    
    public CultivationApiImpl(
        CultivationService cultivationService    ) {
        
        this.cultivationService = cultivationService;
    }

    @Override
    @Operation(summary = "Find Farm by id", description = "Get the farm with the given id")
    public ResponseEntity<CultivationDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Get Farms", description = "Get all farms in the data store")
    public ResponseEntity<Collection<CultivationListDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Get Farms Page", description = "Get {pageSize} farms with for a particular {pageNumber}")
    public ResponseEntity<Page<CultivationListDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Search Farms Page", description = "Get {pageSize} farms for a particular {pageNumber} given a search criteria")
    public ResponseEntity<Page<CultivationListDTO>> pagedSearch(Integer pageNumber, Integer pageSize, CultivationCriteria criteria) throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.search(pageNumber, pageSize, criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Remove farm by id", description = "Remove the farm with the given id")
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Save Farm", description = "Save a farm to data store")
    public ResponseEntity<CultivationDTO> save(CultivationDTO cultivation) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(cultivation, authentication);
            return ResponseEntity.ok(cultivationService.save(cultivation));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Search Farms", description = "Search farms based on the criteria")
    public ResponseEntity<Collection<CultivationListDTO>> search(CultivationCriteria criteria) throws Exception {
        try {
            return ResponseEntity.ok(cultivationService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return cultivationService
     */
    protected CultivationService getCultivationService()
    {
        return this.cultivationService;
    }
}