// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { CropViewComponent } from '@views/crop/details/crop-view';
import { CropViewVarsForm } from '@views/crop/details/crop-view';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@components/table/table';
import { TranslateModule } from '@ngx-translate/core';
import { Loader } from "@shared/loader/loader";
import { FormField } from '@angular/forms/signals';
import { CropDetailsImplComponent } from '@components/crop/crop-details-impl';

@Component({
  selector: 'app-crop-view',
  templateUrl: './crop-view.html',
  styleUrls: ['./crop-view.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    Loader,
    FormField,
    CropDetailsImplComponent,
  ],
})
export class CropViewImplComponent extends CropViewComponent {

    constructor() {
        super();
    }

    doNgOnDestroy(): void {
    }
}