// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { CropController } from '@app/controller/crop/crop-controller';


@Injectable()
export class CropControllerImpl extends CropController {

    constructor() {
        super();
    }

	public doInitialiseEditScreen(form: any): void {
	}

	public doSave(form: any): void {
	}

	public doInitialiseSearchScreen(form: any): void {
	}

	public doSearch(form: any): void {
	}

	public doEditAuthorisation(form: any): void {
	}

	public doDelete(form: any): void {
	}

	public doInitialiseDetailsScreen(form: any): void {
	}

}
