// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.district;

import java.util.Collection;

/**
 * TODO: Model Documentation for District
 * @see District
 */
public interface DistrictDao
{
    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p>
     * This specific flag denotes no transformation will occur.
     */
    public static final int TRANSFORM_NONE = 0;


    /**
     * Transforms the given results to a collection of {@link District}
     * instances (this is useful when the returned results contains a row of data and you want just entities only).
     *
     * @param results the query results.
     */
    public void toEntities(final Collection<?> results);

    /**
     * This constant is used as a transformation flag; entities can be converted automatically into value objects
     * or other types, different methods in a class implementing this interface support this feature: look for
     * an <code>int</code> parameter called <code>transform</code>.
     * <p>
     * This specific flag denotes entities must be transformed into objects of type
     * {@link DistrictVO}.
     */
    public static final int TRANSFORM_DISTRICTVO = 1;

    /**
     * Copies the fields of the specified entity to the target value object. This method is similar to
     * toDistrictVO(), but it does not handle any attributes in the target
     * value object that are "read-only" (as those do not have setter methods exposed).
     * @param source
     * @param target
     */
    public void toDistrictVO(
        District source,
        DistrictVO target);

    /**
     * Converts this DAO's entity to an object of type {@link DistrictVO}.
     * @param entity
     * @return DistrictVO
     */
    public DistrictVO toDistrictVO(District entity);

    /**
     * Converts this DAO's entity to a Collection of instances of type {@link DistrictVO}.
     * @param entities
     * @return Collection<DistrictVO>
     */
    public Collection<DistrictVO> toDistrictVOCollection(Collection<District> entities);

    /**
     * Converts this DAO's entity to an array of instances of type {@link DistrictVO}.
     * @param entities
     * @return DistrictVO[]
     */
    public DistrictVO[] toDistrictVOArray(Collection<?> entities);

    /**
     * Copies the fields of {@link DistrictVO} to the specified entity.
     * @param source
     * @param target
     * @param copyIfNull If FALSE, the value object's field will not be copied to the entity if the value is NULL. If TRUE,
     * it will be copied regardless of its value.
     */
    public void districtVOToEntity(
        DistrictVO source,
        District target,
        boolean copyIfNull);

    /**
     * Converts an instance of type {@link DistrictVO} to this DAO's entity.
     * @param districtVO
     * @return District
     */
    public District districtVOToEntity(DistrictVO districtVO);

    /**
     * Converts a Collection of instances of type {@link DistrictVO} to this
     * DAO's entity.
     * @param instances
     */
    public void districtVOToEntityCollection(Collection<?> instances);

    /**
     * Gets an instance of District from the persistent store.
     * @param id
     * @return District
     */
    public District get(Long id);

    /**
     * <p>
     * Does the same thing as {@link #get(Long)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined in this class then the result <strong>WILL BE</strong> passed through an operation which can
     * optionally transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     *
     * @param transform flag to determine transformation type.
     * @param id the identifier of the entity to get.
     * @return either the entity or the object transformed from the entity.
     */
    public Object get(int transform, Long id);

    /**
     * Loads an instance of District from the persistent store.
     * @param id
     * @return District
     */
    public District load(Long id);

    /**
     * <p>
     * Does the same thing as {@link #load(Long)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined in this class then the result <strong>WILL BE</strong> passed through an operation which can
     * optionally transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     *
     * @param transform flag to determine transformation type.
     * @param id the identifier of the entity to load.
     * @return either the entity or the object transformed from the entity.
     */
    public Object load(int transform, Long id);

    /**
     * Loads all entities of type {@link District}.
     *
     * @return the loaded entities.
     */
    public Collection<District> loadAll();

    /**
     * <p>
     * Does the same thing as {@link #loadAll()} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     *
     * @param transform the flag indicating what transformation to use.
     * @return the loaded entities.
     */
    public Collection<?> loadAll(final int transform);

    /**
     * <p>
     * Does the same thing as {@link #loadAll()} with an
     * additional two arguments called <code>pageNumber</code> and <code>pageSize</code>. The <code>pageNumber</code>
     * argument allows you to specify the page number when you are paging the results and the pageSize allows you to specify the size of the
     * page retrieved.
     * </p>
     *
     * @param pageNumber the page number to retrieve when paging results.
     * @param pageSize the size of the page to retrieve when paging results.
     * @return the loaded entities.
     */
    public Collection<?> loadAll(final int pageNumber, final int pageSize);

    /**
     * <p>
     * Does the same thing as {@link #loadAll(int)} with an
     * additional two arguments called <code>pageNumber</code> and <code>pageSize</code>. The <code>pageNumber</code>
     * argument allows you to specify the page number when you are paging the results and the pageSize allows you to specify the size of the
     * page retrieved.
     * </p>
     *
     * @param transform the flag indicating what transformation to use.
     * @param pageNumber the page number to retrieve when paging results.
     * @param pageSize the size of the page to retrieve when paging results.
     * @return the loaded entities.
     */
    public Collection<?> loadAll(final int transform, final int pageNumber, final int pageSize);

    /**
     * Creates an instance of District and adds it to the persistent store.
     * @param district
     * @return District
     */
    public District create(District district);

    /**
     * <p>
     * Does the same thing as {@link #create(District)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     * @param transform
     * @param district
     * @return Object
     */
    public Object create(int transform, District district);

    /**
     * Creates a new instance of District and adds
     * from the passed in <code>entities</code> collection
     *
     * @param entities the collection of District
     * instances to create.
     *
     * @return the created instances.
     */
    public Collection<District> create(Collection<District> entities);

    /**
     * <p>
     * Does the same thing as {@link #create(District)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entities (into value objects for example). By default, transformation does
     * not occur.
     * </p>
     * @param transform
     * @param entities
     * @return Collection
     */
    public Collection<?> create(int transform, Collection<District> entities);

    /**
     * <p>
     * Creates a new <code>District</code>
     * instance from <strong>all</strong> attributes and adds it to
     * the persistent store.
     * </p>
     * @param code TODO: Model Documentation for District.code
     * @param name TODO: Model Documentation for District.name
     * @return District
     */
    public District create(
        String code,
        String name);

    /**
     * <p>
     * Does the same thing as {@link #create(String, String)} with an
     * additional flag called <code>transform</code>. If this flag is set to <code>TRANSFORM_NONE</code> then
     * the returned entity will <strong>NOT</strong> be transformed. If this flag is any of the other constants
     * defined here then the result <strong>WILL BE</strong> passed through an operation which can optionally
     * transform the entity (into a value object for example). By default, transformation does
     * not occur.
     * </p>
     * @param transform
     * @param code TODO: Model Documentation for District.code
     * @param name TODO: Model Documentation for District.name
     * @return District
     */
    public Object create(
        int transform,
        String code,
        String name);


    /**
     * Updates the <code>district</code> instance in the persistent store.
     * @param district
     */
    public void update(District district);

    /**
     * Create or Update the <code>district</code> instance in the persistent store.
     * @param district
     * @return District
     */
    public District createOrUpdate(District district);

    /**
     * Updates all instances in the <code>entities</code> collection in the persistent store.
     * @param entities
     */
    public void update(Collection<District> entities);

    /**
     * Removes the instance of District from the persistent store.
     * @param district
     */
    public void remove(District district);

    /**
     * Removes the instance of District having the given
     * <code>identifier</code> from the persistent store.
     * @param id
     */
    public void remove(Long id);

    /**
     * Removes all entities in the given <code>entities</code> collection.
     * @param entities
     */
    public void remove(Collection<District> entities);


    /**
     * Allows transformation of entities into value objects
     * (or something else for that matter), when the <code>transform</code>
     * flag is set to one of the constants defined in <code>bw.co.sigmaproduce.district.DistrictDao</code>, please note
     * that the {@link #TRANSFORM_NONE} constant denotes no transformation, so the entity itself
     * will be returned.
     * <p>
     * This method will return instances of these types:
     * <ul>
     *   <li>{@link District} - {@link #TRANSFORM_NONE}</li>
     *   <li>{@link DistrictVO} - {@link #TRANSFORM_DISTRICTVO}</li>
     * </ul>
     *
     * If the integer argument value is unknown {@link #TRANSFORM_NONE} is assumed.
     *
     * @param transform one of the constants declared in {@link bw.co.sigmaproduce.district.DistrictDao}
     * @param entity an entity that was found
     * @return the transformed entity (i.e. new value object, etc)
     * @see #transformEntities(int,Collection)
     */
    public Object transformEntity(final int transform, final District entity);

    /**
     * Transforms a collection of entities using the
     * {@link #transformEntity(int,District)}
     * method. This method does not instantiate a new collection.
     * <p>
     * This method is to be used internally only.
     *
     * @param transform one of the constants declared in <code>bw.co.sigmaproduce.district.DistrictDao</code>
     * @param entities the collection of entities to transform
     * @see #transformEntity(int,District)
     */
    public void transformEntities(final int transform, final Collection<?> entities);

    /**
     * Searches for a single instance of District.
     * @param code the unique code to be used in the search.'
     * @return a single instance of District.
     */
    public District searchUniqueCode(final String code);

    /**
     * Searches for a single instance of District.
     * @param transform the transformation flag.
     * @param code the unique code to be used in the search.
     * @return a value object according the transformation flag.
     */
    public Object searchUniqueCode(final int transform, final String code);

    /**
     * Searches for a single instance of District.
     * @param name the unique name to be used in the search.'
     * @return a single instance of District.
     */
    public District searchUniqueName(final String name);

    /**
     * Searches for a single instance of District.
     * @param transform the transformation flag.
     * @param name the unique name to be used in the search.
     * @return a value object according the transformation flag.
     */
    public Object searchUniqueName(final int transform, final String name);


    // spring-dao merge-point
}