// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.sigmaproduce.crop.issue;

import bw.co.sigmaproduce.crop.CropMapper;
import bw.co.sigmaproduce.crop.type.CropTypeMapper;
import bw.co.sigmaproduce.farm.cultivation.problem.CultivationProblemMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        CropTypeMapper.class,
        CropMapper.class,
        CultivationProblemMapper.class    }
)
public interface CropIssueMapper {
    
    /**
     * Converts this entity to an object of type {@link CropIssueDTO}.
     * @param entity
     * @return CropIssueDTO
     */
    // WARNING! No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    // WARNING! No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    @Mapping(source = "images", target = "images")
    CropIssueDTO toCropIssueDTO(CropIssue entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link CropIssueDTO}.
     * @param entities
     * @return Collection<CropIssueDTO>     */
    List<CropIssueDTO> toCropIssueDTOCollection(Collection<CropIssue> entities);

    /**
     * Converts an instance of type {@link CropIssueDTO} to this DAO's entity.
     * @param cropIssueDTO
     * @return CropIssue
     */
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    CropIssue cropIssueDTOToEntity(CropIssueDTO cropIssueDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    // No conversion for target.updatedDate (can't convert source.getUpdatedDate():java.util.Date to java.util.Date
    // No conversion for target.createdDate (can't convert source.getCreatedDate():java.util.Date to java.util.Date
    @InheritInverseConfiguration
    void updateCropIssueFromCropIssueDTO(CropIssueDTO cropIssueDTO, @MappingTarget CropIssue entity);

}